// <auto-generated />
namespace Fitlife.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class physical_activity_level : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(physical_activity_level));
        
        string IMigrationMetadata.Id
        {
            get { return "201311101907396_physical_activity_level"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
