// <auto-generated />
namespace Fitlife.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class first_migrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_migrate));
        
        string IMigrationMetadata.Id
        {
            get { return "201310191849293_first_migrate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
