// <auto-generated />
namespace Fitlife.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class foodweightsidadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foodweightsidadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201310102111176_food-weights-idadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
