// <auto-generated />
namespace Fitlife.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class user_profile_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_profile_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201311071155121_user_profile_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
