// <auto-generated />
namespace Fitlife.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class secondmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secondmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201310191852358_second-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
